kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssqldata01-cstor-vol-student1
spec:
  storageClassName: sc-cstor-csi-student1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
