apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssqldata01-cstor-vol-student1 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: sc-cstor-csi-student1 
