apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-student1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-sc-student1 
