apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment-snap-student1
spec:
  replicas: 1
  selector:
    matchLabels:
     app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
          runAsUser: 1003
          fsGroup: 1003
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/rhel/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlsecret 
              key: sapassword 
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: pvc-mssqldata01-snap-student
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service-snap-student1
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: NodePort 
