apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-sc-student1
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "cstor-disk-pool"
      - name: ReplicaCount
        value: "2"
      - name: FSType
        value: ext4
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete
volumeBindingMode: Immediate
